### PR TITLE
Implement hot-reload support (default off).

### PR DESCRIPTION
**Pull request by cr1901**
One of the two "must-have" features I need.

When the schematic is updated externally, the screen will be reloaded to reflect your changes. This can be toggled using a new option on the menubar.

### CODE REVIEW

**Comment by galibert** [comment]
Huh, so rather than pressing 'R' you find more amusing to throw a dice and
hope that sview doesn't read an incomplete file and crash?

  OG.

**Comment by cr1901** [comment]
>Huh, so rather than pressing 'R' you find more amusing to throw a dice and
>hope that sview doesn't read an incomplete file and crash?

I'd genuinely rather have the faster reload cycle (without having to move focus to another window) and assume that `mschem` will generate sane output. In any case, the default is to _not_ autoreload so if you don't want the behavior, you simply don't use it :)!

**Comment by galibert** [comment]
mschem generates sane output, but not atomically.  On something big (like
the 68k) sview may try to reload the file before mschem has finished
writing it.  Happened to me from time to time when I went 'r' too fast...

  OG.

**Comment by cr1901** [comment]
>mschem generates sane output, but not atomically.

Ahhh I see... in my case, this is less of a concern because I run everything _except_ `sview` remotely and `rsync` back and forth. But I see what you mean now. I've not had a good day, so let me think more about this when I have the spoons.

**Pull request merged**
